name: smart
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

which dependencies have newer:

dependencies:
  flutter:
   sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  image_picker: ^1.0.7
  http: ^1.1.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.14.0
  permission_handler: ^11.0.1
  path: ^1.8.3
  file_picker: ^8.0.0+1
  platform_file: ^0.1.0
  path_provider: ^2.1.3
  firebase_database: ^10.4.0
  cached_network_image: ^3.3.1
  google_sign_in: ^6.1.6
  dio: ^5.4.3+1
  pdf: ^3.10.8
  image: ^4.1.7
  image_gallery_saver: ^2.0.3
  webview_flutter: ^4.5.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/a.png

