// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATMM685oabo5eBV8ZEcjcvJYGAEtVvK-8',
    appId: '1:80415852932:web:77321b3c2d93370a0ef5d1',
    messagingSenderId: '80415852932',
    projectId: 'smarteco-f7c03',
    authDomain: 'smarteco-f7c03.firebaseapp.com',
    databaseURL:
        'https://smarteco-f7c03-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smarteco-f7c03.appspot.com',
    measurementId: 'G-VC048FBKVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWX6EFwYtmx7h6PkPsAZ09sko1i42cBRM',
    appId: '1:80415852932:android:f847f18e0e5787df0ef5d1',
    messagingSenderId: '80415852932',
    projectId: 'smarteco-f7c03',
    databaseURL:
        'https://smarteco-f7c03-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smarteco-f7c03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK19PeDXjiWjd_d_iKv9-2DgahOtbpurg',
    appId: '1:80415852932:ios:6b9bf5a1cfa964110ef5d1',
    messagingSenderId: '80415852932',
    projectId: 'smarteco-f7c03',
    databaseURL:
        'https://smarteco-f7c03-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smarteco-f7c03.appspot.com',
    iosBundleId: 'com.example.smarteco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK19PeDXjiWjd_d_iKv9-2DgahOtbpurg',
    appId: '1:80415852932:ios:d3fa01df504eb8940ef5d1',
    messagingSenderId: '80415852932',
    projectId: 'smarteco-f7c03',
    databaseURL:
        'https://smarteco-f7c03-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smarteco-f7c03.appspot.com',
    iosBundleId: 'com.example.smarteco.RunnerTests',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK19PeDXjiWjd_d_iKv9-2DgahOtbpurg',
    appId: '1:80415852932:ios:d3fa01df504eb8940ef5d1',
    messagingSenderId: '80415852932',
    projectId: 'smarteco-f7c03',
    databaseURL:
        'https://smarteco-f7c03-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smarteco-f7c03.appspot.com',
  );
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAK19PeDXjiWjd_d_iKv9-2DgahOtbpurg',
    appId: '1:80415852932:ios:d3fa01df504eb8940ef5d1',
    messagingSenderId: '80415852932',
    projectId: 'smarteco-f7c03',
    databaseURL:
        'https://smarteco-f7c03-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'smarteco-f7c03.appspot.com',
  );
}
